---
title: "data stuff"
author: "Anna Leidner"
date: "4/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r libraries}
library(tidyverse)     # for data cleaning and plotting
library(gardenR)       # for Lisa's garden data
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(patchwork)     # for nicely combining ggplot2 graphs  
library(gt)            # for creating nice tables
library(rvest)         # for scraping data
library(robotstxt)     # for checking if you can scrape data
library(janitor)       # for cleaning names
library(baseballr)
library(sportyR)
library(pitchRx)
library(Lahman)

```

```{r my_libraries, include=FALSE}
# Lisa needs this, students don't
library(downloadthis) # for including download buttons for files
library(flair)        # for highlighting code
#library(xaringanExtra)# for small slides and other cool things
```


Pete Alonso every batted ball of 2019. Wanted to draft some visualizations.

```{r}
alonsodata <- read_csv("https://raw.githubusercontent.com/aleidner6/FinalProject/main/alonsodata1.csv") 


alonsodata %>%
  # filter(`Result` == c("single", "double", "triple", "home_run")
  # ) %>%
  #filter(Result == "home_run") %>%
  ggplot(aes(x = `LA (°)`, 
             y = `EV (MPH)`, 
             color = `Result`)) +
  geom_point() +
  labs(title = "Home Run launch angle vs exit velocity", 
       x = "Launch Angle", 
       y = "Exit Velocity")

geom_baseball(league = "MLB")

```


